# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcase1(self):
    # Test name: testcase1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://sandbox.moodledemo.net/")
    # 2 | setWindowSize | 990x549 | 
    self.driver.set_window_size(990, 549)
    # 3 | click | linkText=Seminario de Titulacin | 
    self.driver.find_element(By.LINK_TEXT, "Seminario de Titulacin").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | click | id=single_button6382541ee3a837 | 
    self.driver.find_element(By.ID, "single_button6382541ee3a837").click()
  
def main():
  a = TestDefaultSuite
  a.setup_method()

main()